### ISSUE TITLE
Setup instructions

### ISSUE THREAD

**Issue by palaparthi** [aizazulhaq/instawork-take-home#1]
Hi,

I am trying to follow the setup instructions and running into the below issue while running `/deploy-local.sh`.

<img width="1512" alt="Screenshot 2024-10-30 at 10 11 06 PM" src="https://github.com/user-attachments/assets/6fc34419-6f34-435d-941c-eec8843dbbba">

**Comment by aizazulhaq** [comment]
Hi!

just fixed the issue.

**Comment by palaparthi** [comment]
Adding a member is not working.

https://github.com/user-attachments/assets/6bca95b8-1e5d-4590-9ac2-9f65a53b631b

**Comment by aizazulhaq** [comment]
Hi @palaparthi. Sorry for the inconvenience. I have fixed the issue.

**Comment by palaparthi** [comment]
The issue is not fixed yet.

<img width="757" alt="Screenshot 2024-11-05 at 2 33 12 PM" src="https://github.com/user-attachments/assets/814d2220-6282-400d-be5b-67be2c23469f">

**Comment by aizazulhaq** [comment]
hmm. Look similar to the older error. I just pushed a change in the deploy script to force rebuilding of docker images. Could you also try deleting any older images just in case and redeploy.

**Comment by palaparthi** [comment]
Yes I deleted the older images and re-built, still facing the same issue where it's failing to create a database. These are the postgres container logs

```
sree in ~/projects/iw-take-homes/instawork-take-home on branch main > docker logs postgres-db

PostgreSQL Database directory appears to contain a database; Skipping initialization

2024-11-07 22:09:24.725 UTC [1] LOG:  starting PostgreSQL 14.5 (Debian 14.5-2.pgdg110+2) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2024-11-07 22:09:24.726 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-11-07 22:09:24.726 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-11-07 22:09:24.728 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-11-07 22:09:24.735 UTC [26] LOG:  database system was shut down at 2024-11-07 22:06:58 UTC
2024-11-07 22:09:24.747 UTC [1] LOG:  database system is ready to accept connections
2024-11-07 22:09:25.134 UTC [33] FATAL:  database "mydatabase" does not exist
```

**Comment by aizazulhaq** [comment]
I have updated the deploy script to delete containers and wipe local data. Could you try running it with that?

**Comment by palaparthi** [comment]
Sorry about the late reply, just got back from a vacation. I am still having issues and I think it's related to CORS.
<img width="1504" alt="Screenshot 2024-11-14 at 11 29 09 AM" src="https://github.com/user-attachments/assets/1ae20b70-ea9a-42cf-a0ba-88b60ba55dc2">


<img width="1495" alt="Screenshot 2024-11-14 at 11 29 16 AM" src="https://github.com/user-attachments/assets/2bc4a056-5954-4966-86ac-75b621d987be">

**Comment by aizazulhaq** [comment]
Hi @palaparthi I just set this up on a clean intel mac following the readme. I didn't face this problem. I had already fixed the CORS issue previously during development.
